### ISSUE TITLE
I can't compile on Ubuntu 20.04

### ISSUE THREAD

**Issue by Neflyte49** [cosmos72/twin#82]
Hi I tried it but this error happens:
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++98 -fomit-frame-pointer -fno-strict-aliasing -pipe -Wall -Wshadow -Wno-uninitialized -Wno-unused -Wundef -Wcast-qual -Wcast-align -Wpointer-arith -Wwrite-strings   -o twtest test_stl_chars.o test_stl_fmt.o test_stl_utf8.o test_stl_vector.o test_main.o ../libs/libtstl/libtstl.la 
libtool: link: g++ -g -O2 -std=c++98 -fomit-frame-pointer -fno-strict-aliasing -pipe -Wall -Wshadow -Wno-uninitialized -Wno-unused -Wundef -Wcast-qual -Wcast-align -Wpointer-arith -Wwrite-strings -o .libs/twtest test_stl_chars.o test_stl_fmt.o test_stl_utf8.o test_stl_vector.o test_main.o  ../libs/libtstl/.libs/libtstl.so
/usr/bin/ld: ../libs/libtstl/.libs/libtstl.so: undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:446: twtest] Error 1
make[2]: Leaving directory '/home/israeru/twin/test'
make[1]: *** [Makefile:503: all-recursive] Error 1
make[1]: Leaving directory '/home/israeru/twin/test'
make: *** [Makefile:518: all-recursive] Error 1
uname -a
Linux israeru-Inspiron-5721 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Can you help me?

**Comment by Mirppc** [comment]
That is very odd as it is compiling just fine on Ubuntu 22.04.

Do you have all the dependencies installed?  the development dependencies.

**Comment by rogersavage** [comment]
I'm on Debian 11 and I had the same problem, after installing the dependencies listed in the Twin readme.

When I started trying to track it down, grep revealed that dlerror() is only called once. I commented out line 44 of libs/libtstl/err.cpp and that allowed me to compile. I have Twin running apparently ok at the moment, but I'll chime in again if I can figure out how to actually fix the problem.

**Comment by dgbiotext** [comment]
@rogersavage 

Thanks for your troubleshooting! FWIW, I found that commenting out that line allowed compilation, but the changes to libc.conf did not _not_ help, though I do have dlfcn.h in the place you noted.

Tried on 2 computers -- both Debian 11.6, one i386 one AMD64. Exactly the same problems on both. Happy to have it working!

**Comment by cosmos72** [comment]
It looks like a missing library during linking.
I will fix it ASAP.

**Comment by cosmos72** [comment]
Commit b6e4e4bbae457447792a6d7b899e966c2b6571be should fix this issue.

**Comment by dgbiotext** [comment]
Happy to report vanilla build worked out of the box. Thanks so much!
